version: '3'

services:
   web:
      image: amozgov/app
      ports:
          - "5000:5000"
      environment:
        - DATABASE_HOST=db
        - DATABASE_PORT=5432
        - DATABASE_NAME=first
        - DATABASE_USER=postgres
        - DATABASE_PASSWORD=sova
      depends_on:
        - db
      networks:
        custom_network:
          ipv4_address: 172.20.0.22
   db:
      image: postgres:13
      environment:
        POSTGRES_DB: first
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: sova
      volumes:
        - db_data:/var/lib/postgresql/data
      networks:
        custom_network:
          ipv4_address: 172.20.0.23

volumes:
  db_data: {}

networks:
  custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16